import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import 'antd/dist/reset.css';
import { ConfigProvider } from 'antd';
import QueryProvider from './providers/QueryProvider';

import 'react-toastify/dist/ReactToastify.css';
import { Bounce, ToastContainer } from 'react-toastify';
import Providers from './providers/Providers';

import { Plus_Jakarta_Sans } from 'next/font/google';

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

export const metadata: Metadata = {
  title: 'Menntr',
  description: 'Generated by create next app',
  icons: {
    icon: '/assets/menntrlogo.svg',
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <ConfigProvider>
        <body className={` ${plusJakarta.variable} antialiased`}>
          <Providers>{children}</Providers>
        </body>
      </ConfigProvider>
    </html>
  );
}
