export const institutions = [
  {
    id: 1,
    name: 'ABC Engineering College',
    code: 'ABC-ENG-001',
    plan: 'Premium',
    students: '1200 / 2000',
    status: 'Active',
  },
  {
    id: 2,
    name: 'XYZ Agriculture University',
    code: 'XYZ-AGR-002',
    plan: 'Basic',
    students: '567 / 1000',
    status: 'Active',
  },
  {
    id: 3,
    name: 'PQR Business School',
    code: 'PQR-BUS-003',
    plan: 'Premium',
    students: '890 / 3000',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Sunrise Polytechnic Institute',
    code: 'SUN-POL-004',
    plan: 'Basic',
    students: '300 / 1200',
    status: 'Inactive',
  },
  {
    id: 5,
    name: 'Greenfield Law College',
    code: 'GRN-LAW-005',
    plan: 'Premium',
    students: '785 / 1500',
    status: 'Active',
  },
  {
    id: 6,
    name: 'Bright Medical University',
    code: 'BRT-MED-006',
    plan: 'Basic',
    students: '900 / 1800',
    status: 'Active',
  },
  {
    id: 7,
    name: 'Silver Arts College',
    code: 'SLV-ART-007',
    plan: 'Premium',
    students: '2200 / 2600',
    status: 'Active',
  },
  {
    id: 8,
    name: 'National Commerce School',
    code: 'NAT-COM-008',
    plan: 'Basic',
    students: '400 / 1300',
    status: 'Inactive',
  },
  {
    id: 9,
    name: 'Hilltop Science Academy',
    code: 'HIL-SCI-009',
    plan: 'Premium',
    students: '1500 / 2500',
    status: 'Active',
  },
  {
    id: 10,
    name: 'Oasis Technology College',
    code: 'OAS-TEC-010',
    plan: 'Basic',
    students: '643 / 1100',
    status: 'Active',
  },
  {
    id: 11,
    name: 'Riverdale Engineering School',
    code: 'RIV-ENG-011',
    plan: 'Premium',
    students: '1990 / 3000',
    status: 'Active',
  },
  {
    id: 12,
    name: 'Metro Fine Arts University',
    code: 'MET-ART-012',
    plan: 'Basic',
    students: '560 / 1000',
    status: 'Inactive',
  },
  {
    id: 13,
    name: 'Everest Research Institute',
    code: 'EVR-RES-013',
    plan: 'Premium',
    students: '2400 / 3200',
    status: 'Active',
  },
  {
    id: 14,
    name: 'Brighton Nursing College',
    code: 'BRI-NUR-014',
    plan: 'Basic',
    students: '780 / 1500',
    status: 'Active',
  },
  {
    id: 15,
    name: 'Summit Aviation Academy',
    code: 'SUM-AVI-015',
    plan: 'Premium',
    students: '980 / 1800',
    status: 'Active',
  },
  {
    id: 16,
    name: 'Harmony Music University',
    code: 'HAR-MUS-016',
    plan: 'Basic',
    students: '350 / 900',
    status: 'Inactive',
  },
  {
    id: 17,
    name: 'Global Tourism Institute',
    code: 'GLO-TOU-017',
    plan: 'Premium',
    students: '1230 / 2000',
    status: 'Active',
  },
  {
    id: 18,
    name: 'Apex Pharmacy College',
    code: 'APX-PHA-018',
    plan: 'Basic',
    students: '500 / 1200',
    status: 'Active',
  },
  {
    id: 19,
    name: 'Elite Design Studio University',
    code: 'ELT-DES-019',
    plan: 'Premium',
    students: '1670 / 2400',
    status: 'Active',
  },
  {
    id: 20,
    name: 'Future Robotics Institute',
    code: 'FUT-ROB-020',
    plan: 'Basic',
    students: '420 / 1000',
    status: 'Inactive',
  },
  {
    id: 21,
    name: 'Valley Agriculture College',
    code: 'VAL-AGR-021',
    plan: 'Premium',
    students: '1500 / 2600',
    status: 'Active',
  },
  {
    id: 22,
    name: 'Azure Engineering University',
    code: 'AZU-ENG-022',
    plan: 'Basic',
    students: '840 / 1500',
    status: 'Active',
  },
  {
    id: 23,
    name: 'Coastal Maritime Academy',
    code: 'COS-MAR-023',
    plan: 'Premium',
    students: '620 / 1800',
    status: 'Inactive',
  },
  {
    id: 24,
    name: 'Liberty Dental College',
    code: 'LIB-DEN-024',
    plan: 'Basic',
    students: '710 / 1300',
    status: 'Active',
  },
  {
    id: 25,
    name: 'Phoenix Media University',
    code: 'PHO-MED-025',
    plan: 'Premium',
    students: '3000 / 4000',
    status: 'Active',
  },
  {
    id: 26,
    name: 'Orion Film Academy',
    code: 'ORI-FIL-026',
    plan: 'Basic',
    students: '420 / 1000',
    status: 'Inactive',
  },
  {
    id: 27,
    name: 'Crescent Biotech Institute',
    code: 'CRE-BIO-027',
    plan: 'Premium',
    students: '1800 / 2300',
    status: 'Active',
  },
  {
    id: 28,
    name: 'Royal Hospitality College',
    code: 'ROY-HOS-028',
    plan: 'Basic',
    students: '760 / 1400',
    status: 'Active',
  },
  {
    id: 29,
    name: 'Vertex Civil Engineering College',
    code: 'VTX-CIV-029',
    plan: 'Premium',
    students: '1400 / 2100',
    status: 'Active',
  },
  {
    id: 30,
    name: 'Mentor Software University',
    code: 'MEN-SOF-030',
    plan: 'Basic',
    students: '1200 / 2000',
    status: 'Active',
  },
  {
    id: 31,
    name: 'Pinnacle AI Institute',
    code: 'PIN-AII-031',
    plan: 'Premium',
    students: '900 / 2200',
    status: 'Inactive',
  },
  {
    id: 32,
    name: 'Star Veterinary College',
    code: 'STR-VET-032',
    plan: 'Basic',
    students: '300 / 900',
    status: 'Active',
  },
  {
    id: 33,
    name: 'NextGen Energy Institute',
    code: 'NGN-ENE-033',
    plan: 'Premium',
    students: '500 / 1600',
    status: 'Active',
  },
  {
    id: 34,
    name: 'Urban Architecture School',
    code: 'URB-ARC-034',
    plan: 'Basic',
    students: '789 / 1100',
    status: 'Active',
  },
  {
    id: 35,
    name: 'Premier Fashion College',
    code: 'PRE-FAS-035',
    plan: 'Premium',
    students: '2100 / 2600',
    status: 'Active',
  },
  {
    id: 36,
    name: 'Silverline Textile University',
    code: 'SLV-TEX-036',
    plan: 'Basic',
    students: '500 / 1300',
    status: 'Inactive',
  },
  {
    id: 37,
    name: 'Zenith Political Science College',
    code: 'ZEN-POL-037',
    plan: 'Premium',
    students: '1400 / 2400',
    status: 'Active',
  },
  {
    id: 38,
    name: 'Evergreen Forestry Institute',
    code: 'EVG-FOR-038',
    plan: 'Basic',
    students: '510 / 1400',
    status: 'Active',
  },
  {
    id: 39,
    name: 'Blue Ridge Mining University',
    code: 'BLU-MIN-039',
    plan: 'Premium',
    students: '760 / 1800',
    status: 'Inactive',
  },
  {
    id: 40,
    name: 'United Veterinary School',
    code: 'UNT-VET-040',
    plan: 'Basic',
    students: '830 / 1400',
    status: 'Active',
  },
  {
    id: 41,
    name: 'Glacier Computing College',
    code: 'GLA-COM-041',
    plan: 'Premium',
    students: '900 / 1900',
    status: 'Active',
  },
  {
    id: 42,
    name: 'Newton Mathematics University',
    code: 'NEW-MAT-042',
    plan: 'Basic',
    students: '450 / 1200',
    status: 'Inactive',
  },
  {
    id: 43,
    name: 'Galaxy Cosmetology College',
    code: 'GAL-COS-043',
    plan: 'Premium',
    students: '1100 / 1800',
    status: 'Active',
  },
  {
    id: 44,
    name: 'Epic Physical Education University',
    code: 'EPI-PHY-044',
    plan: 'Basic',
    students: '320 / 800',
    status: 'Active',
  },
  {
    id: 45,
    name: 'Tech Frontier Institute',
    code: 'TEC-FRO-045',
    plan: 'Premium',
    students: '2000 / 2600',
    status: 'Active',
  },
  {
    id: 46,
    name: 'Horizon Environmental College',
    code: 'HOR-ENV-046',
    plan: 'Basic',
    students: '735 / 1400',
    status: 'Active',
  },
  {
    id: 47,
    name: 'Prime Commerce Academy',
    code: 'PRI-COM-047',
    plan: 'Premium',
    students: '1600 / 2200',
    status: 'Inactive',
  },
  {
    id: 48,
    name: 'Crystal Arts & Design College',
    code: 'CRY-ART-048',
    plan: 'Basic',
    students: '520 / 1100',
    status: 'Active',
  },
  {
    id: 49,
    name: 'National Cybersecurity Institute',
    code: 'NAT-CYB-049',
    plan: 'Premium',
    students: '880 / 2000',
    status: 'Active',
  },
  {
    id: 50,
    name: 'AeroSpace Technology University',
    code: 'AER-TEC-050',
    plan: 'Basic',
    students: '600 / 1500',
    status: 'Active',
  },
];
