import { QuestionPerformanceBase } from './QuestionPerformance';

export const questionWiseData: QuestionPerformanceBase[] = [
  {
    question: 'Q1',
    marksObtained: 5,
    totalMarks: 10,
    correctPercentage: 50,
    avgTime: 2.1,
    difficulty: 'Medium',
  },
  {
    question: 'Q2',
    marksObtained: 8,
    totalMarks: 10,
    correctPercentage: 80,
    avgTime: 1.6,
    difficulty: 'Easy',
  },
  {
    question: 'Q3',
    marksObtained: 3,
    totalMarks: 10,
    correctPercentage: 30,
    avgTime: 3.2,
    difficulty: 'Hard',
  },
  {
    question: 'Q4',
    marksObtained: 9,
    totalMarks: 10,
    correctPercentage: 90,
    avgTime: 1.4,
    difficulty: 'Easy',
  },
  {
    question: 'Q5',
    marksObtained: 4,
    totalMarks: 10,
    correctPercentage: 40,
    avgTime: 2.8,
    difficulty: 'Medium',
  },
  {
    question: 'Q6',
    marksObtained: 2,
    totalMarks: 10,
    correctPercentage: 20,
    avgTime: 3.5,
    difficulty: 'Hard',
  },
  {
    question: 'Q7',
    marksObtained: 6,
    totalMarks: 10,
    correctPercentage: 60,
    avgTime: 2.4,
    difficulty: 'Medium',
  },
  {
    question: 'Q8',
    marksObtained: 7,
    totalMarks: 10,
    correctPercentage: 70,
    avgTime: 2.0,
    difficulty: 'Medium',
  },
  {
    question: 'Q9',
    marksObtained: 4,
    totalMarks: 10,
    correctPercentage: 40,
    avgTime: 2.9,
    difficulty: 'Hard',
  },
  {
    question: 'Q10',
    marksObtained: 9,
    totalMarks: 10,
    correctPercentage: 90,
    avgTime: 1.7,
    difficulty: 'Easy',
  },
];
