import DataTable from '../../table/DataTable';
import { Department, departmentColumns } from './department.column';
type Props = {
  globalFilter: string;
  onGlobalFilterChange: (value: string) => void;
  showColumnFilters: boolean;

  onEdit: (row: Department) => void;
};

const data: Department[] = [
  {
    id: 1,
    name: 'Computer Science',
    code: 'CSE',
    category: 'Engineering',
    hod: 'Dr. Rajesh Kumar',
    students: 320,
    faculty: 22,
  },
  {
    id: 2,
    name: 'Information Technology',
    code: 'IT',
    category: 'Engineering',
    hod: 'Dr. Anil Sharma',
    students: 280,
    faculty: 18,
  },
  {
    id: 3,
    name: 'Mechanical Engineering',
    code: 'ME',
    category: 'Engineering',
    hod: 'Dr. Suresh Patil',
    students: 260,
    faculty: 20,
  },
  {
    id: 4,
    name: 'Civil Engineering',
    code: 'CE',
    category: 'Engineering',
    hod: 'Dr. Ravi Verma',
    students: 240,
    faculty: 17,
  },
  {
    id: 5,
    name: 'Electrical Engineering',
    code: 'EEE',
    category: 'Engineering',
    hod: 'Dr. Meena Iyer',
    students: 230,
    faculty: 16,
  },

  {
    id: 6,
    name: 'Electronics Engineering',
    code: 'ECE',
    category: 'Engineering',
    hod: 'Dr. Kiran Rao',
    students: 270,
    faculty: 19,
  },
  {
    id: 7,
    name: 'Artificial Intelligence',
    code: 'AI',
    category: 'Engineering',
    hod: 'Dr. Neha Gupta',
    students: 180,
    faculty: 14,
  },
  {
    id: 8,
    name: 'Data Science',
    code: 'DS',
    category: 'Engineering',
    hod: 'Dr. Aman Khanna',
    students: 200,
    faculty: 15,
  },
  {
    id: 9,
    name: 'Robotics',
    code: 'ROB',
    category: 'Engineering',
    hod: 'Dr. Vikram Singh',
    students: 120,
    faculty: 10,
  },
  {
    id: 10,
    name: 'Automation',
    code: 'AUTO',
    category: 'Engineering',
    hod: 'Dr. Pankaj Joshi',
    students: 110,
    faculty: 9,
  },

  {
    id: 11,
    name: 'Business Administration',
    code: 'MBA',
    category: 'Management',
    hod: 'Dr. Ritu Malhotra',
    students: 300,
    faculty: 25,
  },
  {
    id: 12,
    name: 'Commerce',
    code: 'BCom',
    category: 'Management',
    hod: 'Dr. Sunil Mehta',
    students: 350,
    faculty: 28,
  },
  {
    id: 13,
    name: 'Finance',
    code: 'FIN',
    category: 'Management',
    hod: 'Dr. Alok Jain',
    students: 210,
    faculty: 16,
  },
  {
    id: 14,
    name: 'Marketing',
    code: 'MKT',
    category: 'Management',
    hod: 'Dr. Pooja Nair',
    students: 190,
    faculty: 14,
  },
  {
    id: 15,
    name: 'Human Resources',
    code: 'HR',
    category: 'Management',
    hod: 'Dr. Kavita Rao',
    students: 170,
    faculty: 12,
  },

  {
    id: 16,
    name: 'Economics',
    code: 'ECO',
    category: 'Arts',
    hod: 'Dr. Arvind Kapoor',
    students: 220,
    faculty: 15,
  },
  {
    id: 17,
    name: 'Psychology',
    code: 'PSY',
    category: 'Arts',
    hod: 'Dr. Shalini Bose',
    students: 180,
    faculty: 13,
  },
  {
    id: 18,
    name: 'Sociology',
    code: 'SOC',
    category: 'Arts',
    hod: 'Dr. Deepak Roy',
    students: 160,
    faculty: 11,
  },
  {
    id: 19,
    name: 'Political Science',
    code: 'POL',
    category: 'Arts',
    hod: 'Dr. Nitin Desai',
    students: 140,
    faculty: 10,
  },
  {
    id: 20,
    name: 'History',
    code: 'HIS',
    category: 'Arts',
    hod: 'Dr. Ramesh Kulkarni',
    students: 130,
    faculty: 9,
  },

  {
    id: 21,
    name: 'Physics',
    code: 'PHY',
    category: 'Science',
    hod: 'Dr. Ajay Mishra',
    students: 210,
    faculty: 16,
  },
  {
    id: 22,
    name: 'Chemistry',
    code: 'CHE',
    category: 'Science',
    hod: 'Dr. Lata Menon',
    students: 200,
    faculty: 15,
  },
  {
    id: 23,
    name: 'Mathematics',
    code: 'MAT',
    category: 'Science',
    hod: 'Dr. Sanjay Gupta',
    students: 230,
    faculty: 18,
  },
  {
    id: 24,
    name: 'Biotechnology',
    code: 'BT',
    category: 'Science',
    hod: 'Dr. Richa Agarwal',
    students: 170,
    faculty: 14,
  },
  {
    id: 25,
    name: 'Microbiology',
    code: 'MIC',
    category: 'Science',
    hod: 'Dr. Nilesh Pawar',
    students: 150,
    faculty: 12,
  },

  {
    id: 26,
    name: 'Pharmacy',
    code: 'PHAR',
    category: 'Medical',
    hod: 'Dr. Kunal Shah',
    students: 190,
    faculty: 16,
  },
  {
    id: 27,
    name: 'Nursing',
    code: 'NUR',
    category: 'Medical',
    hod: 'Dr. Anjali Deshpande',
    students: 210,
    faculty: 18,
  },
  {
    id: 28,
    name: 'Physiotherapy',
    code: 'PT',
    category: 'Medical',
    hod: 'Dr. Mohit Bansal',
    students: 160,
    faculty: 13,
  },
  {
    id: 29,
    name: 'Public Health',
    code: 'PH',
    category: 'Medical',
    hod: 'Dr. Sneha Kulkarni',
    students: 140,
    faculty: 11,
  },
  {
    id: 30,
    name: 'Nutrition',
    code: 'NUT',
    category: 'Medical',
    hod: 'Dr. Rekha Iyer',
    students: 120,
    faculty: 9,
  },

  {
    id: 31,
    name: 'Law',
    code: 'LAW',
    category: 'Law',
    hod: 'Dr. Prakash Menon',
    students: 260,
    faculty: 20,
  },
  {
    id: 32,
    name: 'Criminal Law',
    code: 'CRL',
    category: 'Law',
    hod: 'Dr. Vinod Kulkarni',
    students: 140,
    faculty: 11,
  },
  {
    id: 33,
    name: 'Corporate Law',
    code: 'CORP',
    category: 'Law',
    hod: 'Dr. Sheetal Shah',
    students: 180,
    faculty: 14,
  },

  {
    id: 34,
    name: 'Architecture',
    code: 'ARCH',
    category: 'Design',
    hod: 'Dr. Sameer Joshi',
    students: 150,
    faculty: 12,
  },
  {
    id: 35,
    name: 'Interior Design',
    code: 'INT',
    category: 'Design',
    hod: 'Dr. Neelam Kapoor',
    students: 130,
    faculty: 10,
  },
  {
    id: 36,
    name: 'Fashion Design',
    code: 'FD',
    category: 'Design',
    hod: 'Dr. Priti Malhotra',
    students: 120,
    faculty: 9,
  },

  {
    id: 37,
    name: 'Journalism',
    code: 'JRN',
    category: 'Media',
    hod: 'Dr. Rahul Banerjee',
    students: 180,
    faculty: 14,
  },
  {
    id: 38,
    name: 'Mass Communication',
    code: 'MC',
    category: 'Media',
    hod: 'Dr. Snehal Patil',
    students: 200,
    faculty: 16,
  },

  {
    id: 39,
    name: 'Hotel Management',
    code: 'HM',
    category: 'Hospitality',
    hod: 'Dr. Anoop Nair',
    students: 220,
    faculty: 17,
  },
  {
    id: 40,
    name: 'Tourism Management',
    code: 'TM',
    category: 'Hospitality',
    hod: 'Dr. Suman Rao',
    students: 190,
    faculty: 15,
  },

  {
    id: 41,
    name: 'Education',
    code: 'EDU',
    category: 'Education',
    hod: 'Dr. Bhavana Joshi',
    students: 240,
    faculty: 19,
  },
  {
    id: 42,
    name: 'Special Education',
    code: 'SED',
    category: 'Education',
    hod: 'Dr. Alisha Khan',
    students: 120,
    faculty: 10,
  },

  {
    id: 43,
    name: 'Sports Science',
    code: 'SS',
    category: 'Sports',
    hod: 'Dr. Mahesh Patil',
    students: 140,
    faculty: 11,
  },
  {
    id: 44,
    name: 'Physical Education',
    code: 'PE',
    category: 'Sports',
    hod: 'Dr. Rohan Desai',
    students: 160,
    faculty: 13,
  },

  {
    id: 45,
    name: 'Environmental Science',
    code: 'ENV',
    category: 'Science',
    hod: 'Dr. Pranav Kulkarni',
    students: 180,
    faculty: 14,
  },
  {
    id: 46,
    name: 'Geology',
    code: 'GEO',
    category: 'Science',
    hod: 'Dr. Nikhil Soman',
    students: 110,
    faculty: 9,
  },

  {
    id: 47,
    name: 'Statistics',
    code: 'STAT',
    category: 'Science',
    hod: 'Dr. Chetan Kulkarni',
    students: 200,
    faculty: 16,
  },
  {
    id: 48,
    name: 'Astronomy',
    code: 'AST',
    category: 'Science',
    hod: 'Dr. Kunal Verma',
    students: 90,
    faculty: 7,
  },

  {
    id: 49,
    name: 'Linguistics',
    code: 'LING',
    category: 'Arts',
    hod: 'Dr. Ritu Chatterjee',
    students: 100,
    faculty: 8,
  },
  {
    id: 50,
    name: 'Philosophy',
    code: 'PHI',
    category: 'Arts',
    hod: 'Dr. Ashok Sen',
    students: 95,
    faculty: 7,
  },
];

export default function DepartmentsTable({
  globalFilter,
  onGlobalFilterChange,
  showColumnFilters,
  onEdit,
}: Props) {
  return (
    <DataTable
      data={data}
      columns={departmentColumns(
        (row) => onEdit(row),
        (row) => console.log('Delete', row)
      )}
      globalFilter={globalFilter}
      onGlobalFilterChange={onGlobalFilterChange}
      showColumnFilters={showColumnFilters}
    />
  );
}
